{
 "title": "NYC Taxi Fare",
 "time": { "from": "2023-02-28T23:00:00.000Z", "to": "2023-03-31T21:59:59.000Z" },
 "panels": [
  {
   "title": "Abs Max Features Correlation",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", abs_max_features_correlation FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Fare Amount Quantile Metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", column_quantile_metric FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}